/*
 * This source file was generated by the Gradle 'init' task
 */
package org.collatzmark;

public class App {
    public static void main(String[] args) {
        for (int i = 1; i <= 10000; i++) {
            String base = "%d: %s";
            String res = String.format(base, i, collatzSequence(i));
            System.out.println(res);
        }
    }

    static int collatz(int x) {
        if (x % 2 == 0) {
            return x / 2;
        }
        
        return 3 * x + 1;
    }

    static String collatzSequence(int x) {
        String res = "";

        if (x == 1) {
            return res;
        }

        for (int i = collatz(x); i > 1; i = collatz(i)) {
            String base = String.format("%d, ", i);
            res += base;
        }

        return res + "1";
    }
}
